apiVersion: v1
kind: Service
metadata:
  name: despachos-db
  namespace: despachos
spec:
  selector:
    app: despachos-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None
